name: Distribute To Firebase App Distribution
description: Upload artifacts to Firebase App Distribution within seconds
author: Nicholas Wong
branding:
  color: blue
  icon: cloud-drizzle
inputs:
  file:
    description: The release binary file to upload.
    required: true
  app:
    description: Your app's Firebase App ID. You can find the App ID in the Firebase console, on the General Settings page.
    required: true
  token:
    description: A refresh token that's printed when you authenticate your CI environment with the Firebase CLI (read Use the CLI with CI systems for more information).
    required: false
    deprecationMessage: Authenticating with `--token` is deprecated and will be removed in a future major version of `firebase-tools`. Instead, use a service account key with `GOOGLE_APPLICATION_CREDENTIALS` - https://cloud.google.com/docs/authentication/getting-started
  release-notes:
    description: Release notes for this build.
    required: false
  release-notes-file:
    description: Release notes for this build.
    required: false
  testers:
    description: The email addresses of the testers you want to invite.
    required: false
  testers-file:
    description: The email addresses of the testers you want to invite.
    required: false
  groups:
    description: The tester groups you want to invite (refer to Manage testers). Groups are specified using group aliases, which you can look up in the Firebase console.
    required: false
  groups-file:
    description: The tester groups you want to invite (refer to Manage testers). Groups are specified using group aliases, which you can look up in the Firebase console.
    required: false
  debug:
    description: A flag you can include to print verbose log output.
    required: false
    default: false
  cache:
    description: Whether to cache the firebase tools for next job, keeping this on will speed up the build.
    required: false
    default: true
  upgrade:
    description: Whether to attempt to upgrade firebase tools when cache is on, turning this off will speed up the build.
    required: false
    default: true
runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      if: ${{ inputs.cache == 'true' }}
      env: { cache-name: firebase-app-distribution-action }
      with:
        path: /usr/local/bin/firebase
        key: firebase-tools
    - shell: bash
      if: ${{ inputs.credentials == null && inputs.credentials-file != null }}
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS=${{ credentials-file }}
    - shell: bash
      if: ${{ inputs.credentials != null }}
      run: |
        echo "${{ inputs.credentials }}" > .github/credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=.github/credentials.json
    - shell: bash
      run: |
        curl -sL https://firebase.tools | upgrade=${{ inputs.upgrade }} bash
    - shell: bash
      run: |
        /usr/local/bin/firebase appdistribution:distribute \
         --app ${{ inputs.app }} \
         --token "${{ inputs.token }}" \
         --release-notes "${{ inputs.release-notes }}" \
         --release-notes-file "${{ inputs.release-notes-file }}" \
         --testers "${{ inputs.testers }}" \
         --testers-file "${{ inputs.testers-file }}" \
         --groups "${{ inputs.groups }}" \
         --groups-file "${{ inputs.groups-file }}" \
         $(${{ inputs.debug }} && echo "--debug" || echo "") \
         ${{ inputs.file }}
