name: Firebase App Distribution
description: Upload artifacts to Firebase App Distribution
author: Nicholas Wong
branding:
  color: blue
  icon: cloud-drizzle
inputs:
  file:
    description: The release binary file
    required: true
  app:
    description: Your app's Firebase App ID. You can find the App ID in the Firebase console, on the General Settings page.
    required: true
  token:
    description: A refresh token that's printed when you authenticate your CI environment with the Firebase CLI (read Use the CLI with CI systems for more information).
    required: false
  release-notes:
    description: Release notes for this build.
    required: false
  release-notes-file:
    description: Release notes for this build.
    required: false
  testers:
    description: The email addresses of the testers you want to invite.
    required: false
  testers-file:
    description: The email addresses of the testers you want to invite.
    required: false
  groups:
    description: The tester groups you want to invite (refer to Manage testers). Groups are specified using group aliases, which you can look up in the Firebase console.
    required: false
  groups-file:
    description: The tester groups you want to invite (refer to Manage testers). Groups are specified using group aliases, which you can look up in the Firebase console.
    required: false
  debug:
    description: A flag you can include to print verbose log output.
    required: false
runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      env: { cache-name: firebase-app-distribution-action }
      with: 
        path: /usr/local/bin/firebase
        key: firebase-tools
    - shell: bash
      run: curl -sL https://firebase.tools | upgrade=true bash
    - shell: bash
      run: |
        # file: ${{ inputs.file }}
        # app: ${{ inputs.app }}
        # token: ${{ inputs.token }}
        /usr/local/bin/firebase appdistribution:distribute \
          --app ${{ inputs.app }} \
          ${{ inputs.file }}
