name: Main
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run nickwph/firebase-app-distribution-action@v1
        uses: ./
        with:
          file: .github/workflows/assets/app-debug.apk
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
  test-use-credentials-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo '${{ secrets.FIREBASE_CREDENTIALS }}' > ${{ secrets.FIREBASE_CREDENTIALS_FILE }}
      - name: Run nickwph/firebase-app-distribution-action@v1
        uses: ./
        with:
          file: .github/workflows/assets/app-debug.apk
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials-file: ${{ secrets.FIREBASE_CREDENTIALS_FILE }}
  test-no-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run nickwph/firebase-app-distribution-action@v1
        uses: ./
        with:
          file: .github/workflows/assets/app-debug.apk
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          upgrade: false
  test-no-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run nickwph/firebase-app-distribution-action@v1
        uses: ./
        with:
          file: .github/workflows/assets/app-debug.apk
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          cache: false
