name: Main
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run RamiAsia/firebase-app-distribution-action@v1
        uses: ./
        with:
          file: .github/workflows/assets/app-debug.apk
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
  test-share-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run RamiAsia/firebase-app-distribution-action@v1
        uses: ./
        with:
          file: .github/workflows/assets/app-debug.apk
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
      - run: |
         if [ -z "${{ env.SHARE_URL }}" ]; then
           echo "Share URL is empty"
           exit 1
         elif [[ "${{ env.SHARE_URL }}" == *"***"* ]]; then
           echo "Share URL contains invalid characters"
           exit 1
         else
           echo "Share URL: ${{ env.SHARE_URL }}"
         fi
  test-use-credentials-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo '${{ secrets.FIREBASE_CREDENTIALS }}' > ${{ secrets.FIREBASE_CREDENTIALS_FILE }}
      - name: Run RamiAsia/firebase-app-distribution-action@v1
        uses: ./
        with:
          file: .github/workflows/assets/app-debug.apk
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials-file: ${{ secrets.FIREBASE_CREDENTIALS_FILE }}
  test-no-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run RamiAsia/firebase-app-distribution-action@v1
        uses: ./
        with:
          file: .github/workflows/assets/app-debug.apk
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          upgrade: false
  test-no-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run RamiAsia/firebase-app-distribution-action@v1
        uses: ./
        with:
          file: .github/workflows/assets/app-debug.apk
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          cache: false
  test-node-version-16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - name: Run RamiAsia/firebase-app-distribution-action@v1
        uses: ./
        with:
          file: .github/workflows/assets/app-debug.apk
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          cache: false
  test-node-version-18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Run RamiAsia/firebase-app-distribution-action@v1
        uses: ./
        with:
          file: .github/workflows/assets/app-debug.apk
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          cache: false
  test-node-version-21:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - name: Run RamiAsia/firebase-app-distribution-action@v1
        uses: ./
        with:
          file: .github/workflows/assets/app-debug.apk
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          cache: false
